// Generated by Ignite ignite.com/cli

import { StdFee } from "@cosmjs/launchpad";
import { SigningStargateClient, DeliverTxResponse } from "@cosmjs/stargate";
import { EncodeObject, GeneratedType, OfflineSigner, Registry } from "@cosmjs/proto-signing";
import { msgTypes } from './registry';
import { IgniteClient } from "../client"
import { MissingWalletError } from "../helpers"
import { Api } from "./rest";
import { MsgCreateVideo } from "./types/dataocean/dataocean/tx";
import { MsgPlayVideo } from "./types/dataocean/dataocean/tx";


export { MsgCreateVideo, MsgPlayVideo };

type sendMsgCreateVideoParams = {
  value: MsgCreateVideo,
  fee?: StdFee,
  memo?: string
};

type sendMsgPlayVideoParams = {
  value: MsgPlayVideo,
  fee?: StdFee,
  memo?: string
};


type msgCreateVideoParams = {
  value: MsgCreateVideo,
};

type msgPlayVideoParams = {
  value: MsgPlayVideo,
};


export const registry = new Registry(msgTypes);

const defaultFee = {
  amount: [],
  gas: "200000",
};

interface TxClientOptions {
  addr: string
	prefix: string
	signer?: OfflineSigner
}

export const txClient = ({ signer, prefix, addr }: TxClientOptions = { addr: "http://localhost:26657", prefix: "cosmos" }) => {

  return {
		
		async sendMsgCreateVideo({ value, fee, memo }: sendMsgCreateVideoParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgCreateVideo: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgCreateVideo({ value: MsgCreateVideo.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgCreateVideo: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgPlayVideo({ value, fee, memo }: sendMsgPlayVideoParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgPlayVideo: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgPlayVideo({ value: MsgPlayVideo.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgPlayVideo: Could not broadcast Tx: '+ e.message)
			}
		},
		
		
		msgCreateVideo({ value }: msgCreateVideoParams): EncodeObject {
			try {
				return { typeUrl: "/dataocean.dataocean.MsgCreateVideo", value: MsgCreateVideo.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgCreateVideo: Could not create message: ' + e.message)
			}
		},
		
		msgPlayVideo({ value }: msgPlayVideoParams): EncodeObject {
			try {
				return { typeUrl: "/dataocean.dataocean.MsgPlayVideo", value: MsgPlayVideo.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgPlayVideo: Could not create message: ' + e.message)
			}
		},
		
	}
};

interface QueryClientOptions {
  addr: string
}

export const queryClient = ({ addr: addr }: QueryClientOptions = { addr: "http://localhost:1317" }) => {
  return new Api({ baseURL: addr });
};

class SDKModule {
	public query: ReturnType<typeof queryClient>;
	public tx: ReturnType<typeof txClient>;
	
	public registry: Array<[string, GeneratedType]> = [];

	constructor(client: IgniteClient) {		
	
		this.query = queryClient({ addr: client.env.apiURL });		
		this.updateTX(client);
		client.on('signer-changed',(signer) => {			
		 this.updateTX(client);
		})
	}
	updateTX(client: IgniteClient) {
    const methods = txClient({
        signer: client.signer,
        addr: client.env.rpcURL,
        prefix: client.env.prefix ?? "cosmos",
    })
	
    this.tx = methods;
    for (let m in methods) {
        this.tx[m] = methods[m].bind(this.tx);
    }
	}
};

const Module = (test: IgniteClient) => {
	return {
		module: {
			DataoceanDataocean: new SDKModule(test)
		},
		registry: msgTypes
  }
}
export default Module;